### ISSUE TITLE
What are the differencies between rivor  and this one

### ISSUE THREAD

**Issue by markito12** [LarsFL/FortniteScrimBot#1]

**Comment by LarsFL** [comment]
A couple things, here are some of them:

- Couldn't get the original script to work (mostly due to a distinct lack of ;'s)
- Fixed the permissions system (only admins could run it before, even with the setup correct)
- Added a command to go over rules in the voice channel
- Reformatted rich embeds
- Many bug fixes

I'm sure there was more I did, but these are some I could think off
